const maps=[['얼음적금 섬','쉬움','assets/maps/map_1_ice.webp'],['저축빙벽','보통','assets/maps/map_2_saving.webp'],['주식상어 바다','어려움','assets/maps/map_3_shark.webp'],['금리 화산','매우 어려움','assets/maps/map_4_volcano.webp'],['전설의 부자 바다','전설','assets/maps/map_5_legend.webp']];
const fish=[['사이다 붕어','일반','assets/fish/fish_01_saida_bungeo.svg'],['톡톡 잉어','일반','assets/fish/fish_02_toktok_ingeo.svg'],['버블 송어','일반','assets/fish/fish_03_bubble_songeo.svg'],['청량 참치','희귀','assets/fish/fish_04_cheongryang_chamchi.svg'],['스파클 가자미','희귀','assets/fish/fish_05_sparkle_gajami.svg'],['무지개 연어','희귀','assets/fish/fish_06_mujigae_eoneo.svg'],['황금 가오리','전설','assets/fish/fish_07_gold_gagori.svg'],['전설의 고래','전설','assets/fish/fish_08_legend_whale.svg'],['거품 문어','일반','assets/fish/fish_09_octopus.svg'],['탄산 복어','일반','assets/fish/fish_10_tansan_bokeo.svg'],['시원한 새우','일반','assets/fish/fish_11_shrimp.svg'],['빙하 상어','희귀','assets/fish/fish_12_bingha_sangeo.svg'],['사이다 드래곤','전설','assets/fish/fish_13_dragon.svg'],['황금 상어','영웅','assets/fish/fish_14_gold_shark.svg'],['오로라 고래왕','영웅','assets/fish/fish_15_aurora_whale.svg']];
let caught=JSON.parse(localStorage.sbiFishCaught||'[]'); let pointer=0,dir=1,timer=null;
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('on',b.dataset.go===id));}
document.addEventListener('click',e=>{const g=e.target.closest('[data-go]'); if(g)go(g.dataset.go)});
const ml=document.getElementById('mapList'); maps.forEach((m,i)=>{let b=document.createElement('button');b.className='map-card';b.style.backgroundImage=`url(${m[2]})`;b.innerHTML=`<b>${i+1}. ${m[0]}</b><span>${m[1]}</span>`;b.onclick=()=>{document.getElementById('currentMap').innerHTML=`💧 ${i+1}. ${m[0]} <b>${m[1]}</b>`;go('fish')};ml.appendChild(b)});
function renderDex(){const grid=document.getElementById('dexGrid');grid.innerHTML='';fish.forEach((f,i)=>{let ok=caught.includes(i);let c=document.createElement('div');c.className='fish-card '+(ok?'':'lock');c.innerHTML=`<img src="${ok?f[2]:f[2]}"><b>${ok?f[0]:'???'}</b><small>${ok?f[1]:'미획득'}</small>`;grid.appendChild(c)});document.getElementById('dexRate').textContent=Math.round(caught.length/fish.length*100)+'%'}renderDex();
document.getElementById('attendBtn').onclick=()=>{alert('출석 완료! 일반 미끼 +3 지급')};
document.getElementById('biteBtn').onclick=()=>{document.getElementById('gaugeBox').classList.remove('hidden');pointer=0;dir=1;clearInterval(timer);timer=setInterval(()=>{pointer+=dir*2.6;if(pointer>100||pointer<0){dir*=-1;pointer+=dir*2.6}document.getElementById('pointer').style.left=`calc(${pointer}% - 4px)`},16)};
document.getElementById('stopBtn').onclick=()=>{clearInterval(timer);let success=pointer>39&&pointer<62;showResult(success)};
function showResult(success){const modal=document.getElementById('result');const idx=Math.floor(Math.random()*fish.length);const f=fish[idx];document.getElementById('resultTitle').textContent=success?'성공!':'실패!';document.getElementById('resultTitle').style.color=success?'#63d83f':'#ff5e52';document.getElementById('resultImg').src=success?f[2]:'assets/fish/fish_08_legend_whale.svg';document.getElementById('resultName').textContent=success?f[0]:'놓쳤어요';document.getElementById('resultInfo').textContent=success?`${(Math.random()*1.8+.2).toFixed(2)}KG · ${(Math.random()*60+15).toFixed(1)}cm`:'초록 영역에 맞춰 다시 시도하세요';if(success&&!caught.includes(idx)){caught.push(idx);localStorage.sbiFishCaught=JSON.stringify(caught);renderDex()}modal.classList.remove('hidden');document.getElementById('gaugeBox').classList.add('hidden')}
document.getElementById('okBtn').onclick=()=>document.getElementById('result').classList.add('hidden');
