const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const maps=[
{id:1,name:'얼음적금 섬',diff:'쉬움',emoji:'🏔️',unlock:1,rate:1},
{id:2,name:'저축빙벽',diff:'보통',emoji:'💎',unlock:2,rate:1.15},
{id:3,name:'주식상어 바다',diff:'어려움',emoji:'🦈',unlock:3,rate:1.35},
{id:4,name:'금리 화산',diff:'매우 어려움',emoji:'🌋',unlock:5,rate:1.6},
{id:5,name:'전설의 부자 바다',diff:'전설',emoji:'🌌',unlock:8,rate:2}
];
const fish=[
['사이다 붕어','일반','🐟','사이다 호수에서 가장 흔하게 잡히는 붕어. 탄산 기포를 좋아한다.',.28,.75,18,34,45],['톡톡 잉어','일반','🐠','톡 쏘는 기포를 따라다니는 잉어.',.4,1.2,20,38,38],['버블 송어','일반','🐟','작은 거품을 몸에 두르고 헤엄친다.',.25,.9,19,36,35],['거품 문어','일반','🐙','거품을 뿜으며 도망치는 장난꾸러기.',.6,2.1,22,42,25],['탄산 복어','일반','🐡','놀라면 동그랗게 부풀어 오른다.',.35,1.0,24,44,24],['시원한 새우','일반','🦐','얼음장 같은 물살을 좋아하는 새우.',.04,.15,16,30,28],
['청량 참치','희귀','🐟','푸른 바다를 가르는 빠른 참치.',1.5,4.4,45,95,15],['스파클 가자미','희귀','🐠','비늘이 반짝여 멀리서도 보인다.',.8,2.6,42,90,14],['무지개 연어','희귀','🐟','노을빛 강물을 거슬러 오른다.',1.2,3.8,48,105,12],['빙하 상어','희귀','🦈','얼음 바다를 지키는 날렵한 상어.',4,12,70,160,8],['황금 가오리','희귀','🐡','금빛 모래 위를 미끄러지듯 헤엄친다.',1.1,3.2,55,130,9],
['적금 가자미','영웅','🐠','꾸준히 모은 비늘이 단단한 가자미.',1.3,3.5,90,220,5],['금리 장어','영웅','🐍','금리 변동에 따라 몸빛이 바뀐다.',.9,2.8,95,240,4],['배당 문어','영웅','🐙','다리마다 보너스를 들고 다닌다.',2.4,6.8,110,280,3],['황금 해마','영웅','🦑','황금 산호 근처에서만 발견된다.',.35,1.1,120,310,2.4],
['전설의 고래','전설','🐋','큰 행운과 함께 나타나는 전설의 고래.',18,42,250,800,.9],['SBI 청룡어','전설','🐉','사이다 바다 깊은 곳의 수호어.',12,30,300,1000,.45],['부자 고래','전설','🐳','도감을 채운 낚시왕에게만 모습을 보인다.',25,60,500,1600,.25]
].map((f,i)=>({id:i+1,name:f[0],grade:f[1],icon:f[2],desc:f[3],min:f[4],max:f[5],exp:f[6],coin:f[7],rate:f[8]}));
const quiz=[['복리의 의미는?',['시간이 지날수록 이자에 이자가 붙는 효과','현금을 줄이는 효과','세금을 많이 내는 효과'],0],['예금자보호제도는 일반적으로 무엇을 보호할까요?',['금융회사에 맡긴 예금','주식 평가손실','가상자산 수익'],0],['분산투자의 장점은?',['위험을 나누는 데 도움','수익률을 항상 보장','세금을 없앰'],0]];
const init={normalBait:8,goldBait:3,legendBait:1,coin:12345,gem:320,exp:0,level:1,rod:5,map:1,caught:{},dayStreak:0,lastAttend:'',missions:{caught:0,rare:0,coin:0},baitType:'normal'};
let state=JSON.parse(localStorage.getItem('sbiFishingV2')||'null')||init;
function save(){localStorage.setItem('sbiFishingV2',JSON.stringify(state))}
function today(){return new Date().toISOString().slice(0,10)}
function updateTime(){const d=new Date(),h=d.getHours(),m=String(d.getMinutes()).padStart(2,'0');let cls='afternoon',icon='☀️',ampm=h<12?'AM':'PM',hh=h%12||12;if(h>=18||h<6){cls='night';icon='🌙'}else if(h>=16){cls='evening';icon='🌇'}else if(h<12){cls='morning';icon='☀️'}$('#app').className='app '+cls;$('#clock').textContent=`${icon} ${ampm} ${String(hh).padStart(2,'0')}:${m}`}
function render(){updateTime();$('#bait').textContent=state.normalBait+state.goldBait+state.legendBait;$('#normalBait').textContent=state.normalBait;$('#goldBait').textContent=state.goldBait;$('#legendBait').textContent=state.legendBait;$('#coin').textContent=state.coin.toLocaleString();$('#gem').textContent=state.gem;$('#level').textContent=state.level;$('#rodLevel').textContent=state.rod;$('#upgradeCost').textContent=upgradeCost();$('#expBar').style.width=(state.exp%100)+'%';const map=maps.find(m=>m.id===state.map);$('#currentMapChip').textContent=`${map.id}. ${map.name} · ${map.diff}`;renderMissions();renderAttendance();renderMap();renderBook();}
function renderMissions(){const ms=[['물고기 5마리 잡기',state.missions.caught,5],['희귀 이상 1마리 잡기',state.missions.rare,1],['100 포인트 획득',state.missions.coin,100]];$('#missionList').innerHTML=ms.map(m=>`<div class="mission-row"><b>${m[0]}</b><span style="float:right">${Math.min(m[1],m[2])}/${m[2]}</span><div class="bar"><i style="width:${Math.min(100,m[1]/m[2]*100)}%"></i></div></div>`).join('')}
function renderAttendance(){let html='';for(let i=1;i<=7;i++){html+=`<div class="day ${state.dayStreak>=i?'done':''} ${state.dayStreak+1===i?'today':''}">${i}일<br>${i===7?'💎':'🪱'}</div>`}$('#attendanceList').innerHTML=html;$('#attendanceBtn').disabled=state.lastAttend===today();$('#attendanceBtn').textContent=state.lastAttend===today()?'출석 완료':'오늘 출석'}
function renderMap(){$('#worldMap').innerHTML=maps.map(m=>`<button class="map-card ${state.level<m.unlock?'locked':''} ${state.map===m.id?'selected':''}" data-id="${m.id}"><div class="island">${m.emoji}</div><h2>${m.id}. ${m.name}</h2><p>난이도 ${m.diff}</p><p>${state.level<m.unlock?'🔒 LV.'+m.unlock+' 해제':'선택 가능'}</p></button>`).join('')}
function renderBook(grade='all'){const caught=Object.keys(state.caught).length;$('#collectRate').textContent=Math.round(caught/fish.length*100)+'%';$('#fishGrid').innerHTML=fish.filter(f=>grade==='all'||f.grade===grade).map(f=>{const has=state.caught[f.id];return `<div class="fish-cell ${has?'':'locked'}"><div class="icon">${has?f.icon:'❔'}</div><b>${has?f.name:'???'}</b><br><span class="badge ${f.grade}">${f.grade}</span><p>${has?Math.max(...has.weights).toFixed(2)+'KG':'미획득'}</p></div>`}).join('')}
function pickFish(){const baitBonus={normal:1,gold:1.8,legend:3}[state.baitType];const map=maps.find(m=>m.id===state.map);let pool=fish.map(f=>{let w=f.rate;if(f.grade!=='일반')w*=baitBonus;if(f.grade==='전설')w*=map.rate; if(map.id>=3&&['희귀','영웅','전설'].includes(f.grade))w*=1.3; return {...f,w}});let sum=pool.reduce((a,b)=>a+b.w,0),r=Math.random()*sum;for(const f of pool){r-=f.w;if(r<=0)return f}return pool[0]}
function consumeBait(){const key=state.baitType+'Bait';if(state[key]<=0){alert('선택한 미끼가 부족합니다.');return false}state[key]--;return true}
function catchFish(){if(!consumeBait())return;const f=pickFish();const weight=+(f.min+Math.random()*(f.max-f.min)).toFixed(2);const length=+(weight*45+10+Math.random()*8).toFixed(1);const isNew=!state.caught[f.id];state.caught[f.id]=state.caught[f.id]||{count:0,weights:[]};state.caught[f.id].count++;state.caught[f.id].weights.push(weight);state.coin+=f.coin;state.exp+=f.exp;while(state.exp>=100){state.exp-=100;state.level++;state.gem+=5}state.missions.caught++;if(f.grade!=='일반')state.missions.rare++;state.missions.coin+=f.coin;showCatch(f,weight,length,isNew);save();render()}
function showCatch(f,w,l,isNew){$('#newBadge').hidden=!isNew;$('#caughtIcon').textContent=f.icon;$('#caughtName').textContent=f.name;$('#caughtGrade').textContent=f.grade;$('#caughtGrade').className='grade badge '+f.grade;$('#caughtWeight').textContent=w.toFixed(2)+'KG';$('#caughtLength').textContent=l.toFixed(1)+'cm';$('#caughtDesc').textContent=f.desc;$('#expGain').textContent=f.exp;$('#coinGain').textContent=f.coin;$('#catchModal').hidden=false}
function upgradeCost(){return state.rod*120}function answerQuiz(i){const q=quiz[new Date().getDate()%quiz.length];if(i===q[2]){state.normalBait+=3;alert('정답! 일반 미끼 3개 지급');}else alert('아쉬워요. 다시 도전해보세요.');save();render()}function renderQuiz(){const q=quiz[new Date().getDate()%quiz.length];$('#quizQuestion').textContent='Q. '+q[0];$('#quizOptions').innerHTML=q[1].map((o,i)=>`<button onclick="answerQuiz(${i})">${i+1}. ${o}</button>`).join('')}
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view+'View').classList.add('active');if(b.dataset.view==='quiz')renderQuiz();});
$('#fishBtn').onclick=catchFish;$('#closeModal').onclick=$('#confirmCatch').onclick=()=>$('#catchModal').hidden=true;$('#attendanceBtn').onclick=()=>{if(state.lastAttend===today())return;state.lastAttend=today();state.dayStreak=state.dayStreak%7+1;state.normalBait+=5;if(state.dayStreak===7)state.gem+=50;save();render()};$('#claimMission').onclick=()=>{if(state.missions.caught>=5&&state.missions.rare>=1&&state.missions.coin>=100){state.goldBait+=2;state.coin+=200;state.missions={caught:0,rare:0,coin:0};alert('미션 완료! 황금 미끼 2개와 200코인 지급');save();render()}else alert('아직 완료하지 못한 미션이 있습니다.')};$$('.bait-card').forEach(b=>b.onclick=()=>{$$('.bait-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.baitType=b.dataset.bait;save()});document.addEventListener('click',e=>{const m=e.target.closest('.map-card');if(m){const id=+m.dataset.id,mp=maps.find(x=>x.id===id);if(state.level<mp.unlock)return alert('레벨이 부족합니다.');state.map=id;save();render()}const t=e.target.closest('.tab');if(t){$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');renderBook(t.dataset.grade)}});$('#upgradeBtn').onclick=()=>{const c=upgradeCost();if(state.coin<c)return alert('코인이 부족합니다.');state.coin-=c;state.rod++;save();render()};$('#resetBtn').onclick=()=>{if(confirm('저장 데이터를 초기화할까요?')){localStorage.removeItem('sbiFishingV2');location.reload()}};setInterval(updateTime,30000);render();
