---
#-------------------------------
# General Site Settings

title: JUNSEOK
logo:
author: themefisher
description: this is meta description
email: mhjj315@gmail.com
phone: +82 1020468380
address: 780, Taejang-ro, Gimpo-si, Gyeonggi-do, Republic of Korea
copyright: Copyright &copy; 2023 Developed by JunSeok

menu:
  - { name: About, link: "/about" }
  # - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: HI! <br> I'm UI/UX Publisher <br> JunSeok:)

social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: 안녕하세요! 웹 퍼블리셔 어준석입니다.  HTML, CSS, Script 등 프레임워크 환경에서 컴포넌트 단위의 마크업 작업을 능숙하게 할 수 있어요. 어디에서도 잘 보이는 반응형은 물론 웹 접근성과 웹 표준을 고려한 웹 페이지를 그려내기 위해 늘 고민합니다. 맡은 프로젝트의 목적을 우선적으로 생각하며, 함께하는 팀원 들과의 원활한 협업을 중요하게 생각해요. 다양한 직군의 동료들과 함께 멋지고 즐거운 UI/UX를 만드는 데 관심이 많습니다.

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Services Section
work-process:
  - title: "UI Development"
    icon: "assets/images/icons/plan.png"
    content: "웹 퍼블리싱에 대한 이해도를 바탕으로 재활용과 유지보수가 쉬운 코드를 짤 수 있도록 여러 가능성 및 예외 상황을 고려하며 개발을 진행합니다."

  - title: "UX Experience"
    icon: "assets/images/icons/design.png"
    content: "고객 입장에서의 사용성을 고려하며 웹 접근성, 웹 표준, SEO 최적화는 물론 UI가이드를 수립하고 통일성 있고 일관적인 UX를 제공할수 있도록 끊임없이 생각합니다."

  - title: "Co-Work"
    icon: "assets/images/icons/print.png"
    content: "프로젝트의 목적성을 우선적으로 고려하며 동료들과의 협업을 중요하게 생각합니다. 서로의 생각과 의견을 끊임없이 공유하며 결과물을 도출해냅니다."

# My Team Section
team:
  - title: "Jack Schenziwe"
    image: "assets/images/team/member-1.png"
    designation: "Project Manager"

  - title: "Julias Carlie"
    image: "assets/images/team/member-2.png"
    designation: "Web Developer"

  - title: "John Doe"
    image: "assets/images/team/member-3.png"
    designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: HTML, color: "#fdb157", value: "90%" }
  - { name: CSS, color: "#9473e6", value: "90%" }
  - { name: JQUERY, color: "#bdecf6", value: "80%" }
  - { name: JAVASCRIPT, color: "#ffbcaa", value: "60%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Eilab,
      icon: "eilab_logo.jpg",
      date: "2014. 11 ~ 2018. 03",
      organization: "First",
    }
  - {
      name: JEJUair,
      icon: "jejuair_logo.jpg",
      date: "2018. 08 ~ ing",
      organization: "Second",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Marters in UX Design,
      date: "2006",
      organization: "Masassusets Institute of Technology",
    }
  - {
      name: Honours in Fine Arts,
      date: "2004",
      organization: "Harvard University",
    }
  - {
      name: Higher Secondary Certificat,
      date: "2000",
      organization: "Cardiff School",
    }
  - {
      name: Secondary School Certificate,
      date: "1998",
      organization: "Cardiff School",
    }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: UI Development,
      icon: ti-palette,
      description: "웹 퍼블리싱에 대한 이해도를 바탕으로 재활용과 유지보수가 쉬운 코드를 짤 수 있도록 여러 가능성 및 예외 상황을 고려하며 개발을 진행합니다.",
      active: ,# Add true to select section
    }
  - {
      name: UX Experience,
      icon: ti-vector,
      description: "고객 입장에서의 사용성을 고려하며 웹 접근성, 웹 표준, SEO 최적화는 물론 UI가이드를 수립하고 통일성 있고 일관적인 UX를 제공할수 있도록 끊임없이 생각합니다.",
      active: true, # Add true to select section
    }
  - {
      name: Co-Work,
      icon: ti-panel,
      description: "프로젝트의 목적성을 우선적으로 고려하며 동료들과의 협업을 중요하게 생각합니다. 서로의 생각과 의견을 끊임없이 공유하며 결과물을 도출해냅니다.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Skills Logo Slider Section

skills-slider-items:
  - logo: "assets/images/skills-logo/skills-logo-1.svg"
    url: "#"

  - logo: "assets/images/skills-logo/skills-logo-2.svg"
    url: "#"

  - logo: "assets/images/skills-logo/skills-logo-3.svg"
    url: "#"

  - logo: "assets/images/skills-logo/skills-logo-4.svg"
    url: "#"

  - logo: "assets/images/skills-logo/skills-logo-5.svg"
    url: "#"

  - logo: "assets/images/skills-logo/skills-logo-6.svg"
    url: "#"

  - logo: "assets/images/skills-logo/skills-logo-7.svg"
    url: "#"

  - logo: "assets/images/skills-logo/skills-logo-8.svg"
    url: "#"

  - logo: "assets/images/skills-logo/skills-logo-9.svg"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: mhjj315@gmail.com
